### ISSUE TITLE
Remove unneccessary synchronization on the server side

### ISSUE THREAD

**Issue by akurilov** [rclongloaf/project1#1]
The synchronization distorts the results significantly. The chart will change so please update it also.

**Comment by rclongloaf** [comment]
Yes, it will faster. RMI has synchronization, but only for one client program. I'll remove it, because in this test only one client is working. Otherwise synchronization is needed here, i think.

**Comment by akurilov** [comment]
We don't care about the returned values and their distribution. Synchronized method forces the server to respond sequentially and the resulting count of the client threads doesn't point to the real CPU parallelism level.

**Comment by rclongloaf** [comment]
I updated the results. Now the operating time of the function has decreased relative to the data transfer time, so the best performance is achieved with 30 threads.
